#! /bin/sh

screen_width=$(sres -W)
panel_height=20
font="terminess:pixelsize=9,-*-tewi-medium-*-normal-*-11-*-*-*-*-*-*-*"
icons=$HOME/.pydzen/xbm
color_se='#03A9F4'
color_sf='#f9f9f9'

# Light theme
#color_fg='#555555'
#color_bg='#EDEDED'

# Dark theme
color_fg='#B0B0B0'
#color_bg='#263238'
color_bg='#242424'
